# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRHXkJx6zMMnNG2fLGe4YQdbVjxan2Dy
"""

import sqlite3

# Create database
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Create sales table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# Insert sample data
data = [
    ("Pen", 10, 5),
    ("Pen", 20, 5),
    ("Notebook", 15, 20),
    ("Notebook", 10, 20),
    ("Pencil", 30, 2),
]

cursor.executemany("INSERT INTO sales VALUES (?, ?, ?)", data)

conn.commit()
conn.close()

print("Database created successfully!")

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# 1. Connect to database
conn = sqlite3.connect("sales_data.db")

# 2. Write SQL query
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

# 3. Load results into pandas
df = pd.read_sql_query(query, conn)

# 4. Print results
print("=== SALES SUMMARY ===")
print(df)

# 5. Plot chart
plt.figure(figsize=(6,4))
plt.bar(df["product"], df["revenue"])
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.title("Revenue by Product")
plt.tight_layout()
plt.show()

# Optional: Save chart
plt.savefig("sales_chart.png")

# Close DB connection
conn.close()