# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMJbTfe87U_aVV-YC5KXmHCrxggahmXp
"""

import pandas as pd

# Load data
df = pd.read_csv("/content/superstore_sample.csv")

# Convert date column
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["MonthYear"] = df["Order Date"].dt.strftime("%b-%Y")

# Basic summary
print(df.head())
print(df.describe())

# Save cleaned file
df.to_csv("Cleaned_Superstore.csv", index=False)

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/superstore_sample.csv")
df.head()

df["Order Date"] = pd.to_datetime(df["Order Date"], errors='coerce')
df = df.dropna(subset=["Order Date"])

df["MonthYear"] = df["Order Date"].dt.strftime("%b-%Y")

# Group by MonthYear
monthly_sales = df.groupby("MonthYear")["Sales"].sum().reset_index()

# Convert MonthYear to datetime for proper sorting
monthly_sales["MonthYear_dt"] = pd.to_datetime(monthly_sales["MonthYear"], format="%b-%Y")

# Sort using this datetime column
monthly_sales = monthly_sales.sort_values("MonthYear_dt")

# Plot
plt.figure(figsize=(12,6))
plt.plot(monthly_sales["MonthYear"], monthly_sales["Sales"], marker='o')
plt.xticks(rotation=45)
plt.title("Sales Over Time (Month-Year)")
plt.xlabel("Month-Year")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("line_sales_over_time.png")
plt.show()

region_sales = df.groupby("Region")["Sales"].sum().reset_index()

plt.figure(figsize=(8,6))
plt.bar(region_sales["Region"], region_sales["Sales"])
plt.title("Sales by Region")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("bar_sales_by_region.png")
plt.show()

category_sales = df.groupby("Category")["Sales"].sum()

plt.figure(figsize=(8,6))
plt.pie(category_sales, labels=category_sales.index, autopct='%1.1f%%')
centre_circle = plt.Circle((0,0),0.70,fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

plt.title("Sales by Category (Donut Chart)")
plt.tight_layout()
plt.savefig("donut_sales_by_category.png")
plt.show()