# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4DqSye1I-zNhC_5e9QYeUCeXWPlL8q7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("train.csv")
df.head()

df.info()

df.describe()

df.dtypes

df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df['Cabin'].fillna("Unknown", inplace=True)

df.hist(figsize=(12,8))
plt.show()

sns.histplot(df['Age'], kde=True)

sns.countplot(x='Survived', data=df)

sns.countplot(x='Pclass', hue='Survived', data=df)

sns.scatterplot(x='Age', y='Fare', hue='Survived', data=df)

corr = df.corr(numeric_only=True)
corr

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

plt.figure(figsize=(10,6))

corr = df.corr(numeric_only=True)   # calculate correlation matrix

sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

sns.pairplot(df[['Survived','Age','Fare','Pclass']], hue='Survived')

plt.figure(figsize=(10,6))
sns.boxplot(data=df[['Age','Fare']])
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Select numerical columns + Survived
cols = ['Survived', 'Age', 'Fare', 'Pclass']

sns.pairplot(df[cols], hue='Survived')
plt.show()

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival Rate by Passenger Class")
plt.show()

sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age Distribution by Survival")
plt.show()

sns.boxplot(x='Survived', y='Fare', data=df)
plt.title("Fare Distribution by Survival")
plt.show()

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.pairplot(df[['Survived','Age','Fare','Pclass']], hue='Survived')
plt.show()