# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hS3cQQav_wQmISmIcXN7s0Z8bvxlDgS0
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/mall_customers_raw.csv')

# View first few rows
print(df.head())

print(df.isnull().sum())

# Option 1: Remove rows with missing values
df = df.dropna()

# Option 2: Fill missing values with mean or mode
df['Age'] = df['Age'].fillna(df['Age'].mean())

df = df.drop_duplicates()

df['Gender'] = df['Gender'].str.strip().str.lower()

df.rename(columns={'date': 'Date'}, inplace=True)

print(df.head())

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Annual Income (k$)'] = df['Annual Income (k$)'].fillna(df['Annual Income (k$)'].mean())
df['Spending Score (1-100)'] = df['Spending Score (1-100)'].fillna(df['Spending Score (1-100)'].mean())

# For Gender (categorical)
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

df = df.drop_duplicates()

df['Gender'] = df['Gender'].str.strip().str.lower()

df['Gender'] = df['Gender'].str.title()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.dtypes

df['age'] = df['age'].astype(int)
df['customerid'] = df['customerid'].astype(int)

df.to_csv('mall_customers_cleaned.csv', index=False)